service: privian-analytics-cloudwatch
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  lambdaHashingVersion: '20201221'
  memorySize: 128
  timeout: 15
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricData
      Resource: "*"
  cloudFront:
    cachePolicies:
      myCachePolicy:
        DefaultTTL: 60
        MinTTL: 30
        MaxTTL: 3600
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - CloudFront-Viewer-Country
          QueryStringsConfig:
            QueryStringBehavior: all

plugins:
  - serverless-offline

package:
  excludeDevDependencies: true
  exclude:
    - .git/**
    - node_modules/aws-sdk/**
    - README.md

functions:
  api:
    handler: handler.handler
    events:
      - cloudFront:
          eventType: origin-request
          includeBody: true
          origin: s3://bucketname.s3.amazonaws.com/files
          cachePolicy:
            name: myCachePolicy
          behavior:
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'
              - 'PUT'
              - 'PATCH'
              - 'POST'
              - 'DELETE'
            CachedMethods:
              - 'GET'
              - 'HEAD'
              - 'OPTIONS'


